name: Dummy checks
on:
  push:
    branches:
      - master # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  \[GitHub project - Gradle\] SonarQube Code Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
  \[GitHub project - Maven\] SonarQube Code Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
  \[GitHub project - dotnet\] SonarQube Code Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
  \[GitHub project\] SonarQube Code Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0