name: Dummy QG
on:
  push:
    branches:
      - master # or the name of your main branch
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  check-what-to-build:
    name: Check what to build
    outputs:
      run_cli: ${{ steps.check_files.outputs.run_cli }}
      run_maven: ${{ steps.check_files.outputs.run_maven }}
      run_gradle: ${{ steps.check_files.outputs.run_gradle }}
      run_dotnet: ${{ steps.check_files.outputs.run_dotnet }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: check branch and modified files
        id: check_files
        run: |
          echo "=== Checking branch name"
          branch_name=`echo ${GITHUB_REF#refs/heads/}`
          shopt -s extglob
          if [[ $branch_name == "(f/).*" ]]; then
            echo "=== Branch name '$branch_name' hints at full rebuild"
            read -r build_cli build_maven build_gradle build_dotnet <<< "true true true true"
          else
            echo "=== Smart rebuild"
            read -r build_cli build_maven build_gradle build_dotnet <<< "false false false false"
            git diff --name-only HEAD^ HEAD > files.txt
            while IFS= read -r file
            do
              echo $file
              if [[ "$file" == ".github/workflows/build.yml" ]]; then
                echo "=== Main workflow file changed --> full rebuild"
                read -r build_cli build_maven build_gradle build_dotnet <<< "true true true true"
                break
              fi
              dir=$(echo $file|cut -d '/' -f 1)
              if [[ $dir == comp-cli ]]; then
                build_cli="true"
              elif [[ $dir == comp-maven ]]; then
                build_maven="true"
              elif [[ $dir == comp-gradle ]]; then
                build_gradle="true"
              elif [[ $dir == comp-dotnet ]]; then
                build_dotnet="true"
              fi
            done < files.txt
          fi
          echo "::set-output name=run_cli::$build_cli"
          echo "::set-output name=run_maven::$build_maven"
          echo "::set-output name=run_gradle::$build_gradle"
          echo "::set-output name=run_dotnet::$build_dotnet"

  sq-gradle:
    needs: check-what-to-build
    if: needs.check-what-to-build.outputs.run_gradle == 'false'
    runs-on: ubuntu-latest
    name: "[GitHub project - Gradle] SonarQube Code Analysis"
    steps:
      - name: Exit with success
        run: exit 0
  sq-maven:
    needs: check-what-to-build
    if: needs.check-what-to-build.outputs.run_maven == 'false'
    name: "[GitHub project - Maven] SonarQube Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
  sq-dotnet:
    needs: check-what-to-build
    if: needs.check-what-to-build.outputs.run_dotnet == 'false'
    name: "[GitHub project - .Net Core] SonarQube Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0
  sq-cli:
    needs: check-what-to-build
    if: needs.check-what-to-build.outputs.run_cli == 'false'
    name: "[GitHub project] SonarQube Code Analysis"
    runs-on: ubuntu-latest
    steps:
      - name: Exit with success
        run: exit 0